server:
  port: 8061

spring:
  application:
    name: service-competition
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition2.0?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    password: 12345
    database: 0
    host: 127.0.0.1
    port: 6379
  thymeleaf:
    cache: false

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:  #指定Mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: on  #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: zust.competition.sys

upload:
  # 上传图片的路径
  location:
    pics: F:/JavaEEPro/upload/pictures/
    files: F:/JavaEEPro/upload/files/
  # 访问图片图片的路径
  route:
    pics: /upload-image/**
    files: /upload-file/**

gateway:
  route:
    name: /competition-serv