server:
  port: 8081
spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:  #指定Mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: on  #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: zust.competition.sys
